version: "2"
services:
  javatechiemongodb:
    image: mongo:latest
    container_name: "javatechiemongodb"
    ports:
      - 27017:27017
  springboot-mrpacep:
    image: springboot-mrpacep:1.0
    container_name: springboot-mrpacep
    ports:
      - 8080:8080
    links:
      - javatechiemongodb