version: "2"
services:
  mrpacemongodbs:
    image: mongo:latest
    container_name: "mrpacemongodbs"
    ports:
      - 27017:27017

  springboot-mrpaces:
    image: springboot-mrpace:1.0
    container_name: springboot-mrpaces
    ports:
      - 8080:8080
    links:
      - mrpacemongodbs